### PR TITLE
Error in transmit: request() got multiple values for keyword argument 'headers'

### PR DESCRIPTION
**Pull request by beyonddc**
kwargs JSON object has another header.

```
[ERROR   ][server_fuzzer._transmit] Error in transmit: request() got multiple values for keyword argument 'headers'
[ERROR   ][server._start] Error occurred while fuzzing: TypeError("request() got multiple values for keyword argument 'headers'",)
[ERROR   ][server._start] Traceback (most recent call last):
```

Because of the enhancement that was made to allow specification of the
API Key thru environmental variable as header, the side-effect is there
are two headers being sent to the requests.request() call.

To resolve the issue, we can check if header exist in kwargs JSON
object, if so then we merge both headers into a single combined header
then pass it as an input to requests.request() call.

### CODE REVIEW

**Comment by buzzdeee** [comment]
I made some changes to only set the headers, when the environment variable is given, now your patch conflicts. Can you rebase the fix to master again?
Otherwise I'm going to merge it in, in worst case somehow manually.

**Comment by beyonddc** [comment]
> I made some changes to only set the headers, when the environment variable is given, now your patch conflicts. Can you rebase the fix to master again?
> Otherwise I'm going to merge it in, in worst case somehow manually.

Yes, I can take care it but take a look at my comment to your latest commit first.  You might need to do another commit.  I will take care the conflict once it is all set.  Thanks

**Comment by buzzdeee** [comment]
Alright, that line removed, should be all fine now to rebase.

thanks

**Comment by beyonddc** [comment]
> Alright, that line removed, should be all fine now to rebase.
> 
> thanks

Should be all set now.  Thanks

**Comment by buzzdeee** [comment]
thank you!

**Pull request merged**
